In [1]:
import pandas as pd

CSV_PATH = "E:\\study\\bachelor\\temp-files\\data\\Obtain data\\dataframes\\2023_summer_01.csv"

In [26]:
import pandas as pd
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image

class CustomDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):

        img_path = self.dataframe.iloc[idx]['image_path']
        speed = self.dataframe.iloc[idx]['speed:']
        cur_gear = self.dataframe.iloc[idx]['curGear:']
        side_speed = self.dataframe.iloc[idx]['sideSpeed:']
        input_value = self.dataframe.iloc[idx]['inputSteer:']
        
        image = Image.open(img_path)
        
        if self.transform:
            image = self.transform(image)
        
        return image, speed, cur_gear, side_speed, input_value

df = pd.read_csv(CSV_PATH)

transform = transforms.Compose([transforms.Resize((224, 224)),
                                transforms.ToTensor()])

In [27]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, shuffle=False)

train_dataset = CustomDataset(dataframe=train_df, transform=transform)
test_dataset = CustomDataset(dataframe=test_df, transform=transform)

train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)


In [29]:
for batch in test_loader:
    image, speed, cur_gear, side_speed, input_value = batch
    print(speed)

tensor([414.3712, 418.2422, 418.2422, 421.8478, 426.6600, 426.6600, 430.7733,
        430.7733, 435.1370, 439.4427, 439.4427, 443.8688, 443.8688, 441.9210,
        441.9210, 438.6070, 438.6070, 430.6454, 430.6454, 420.8506, 420.8506,
        422.3002, 422.3002, 426.7839, 426.7839, 430.6572, 430.6572, 434.2073,
        434.2073, 439.2469, 439.2469, 450.2664], dtype=torch.float64)
tensor([450.2664, 450.1349, 449.1153, 449.1153, 449.2356, 449.2356, 450.1953,
        450.1953, 452.5691, 456.0013, 456.0013, 460.8422, 460.8422, 466.6814,
        466.6814, 469.0249, 469.0249, 468.5157, 468.5157, 467.0493, 467.0493,
        466.3409, 465.8801, 465.8801, 465.2509, 465.2509, 463.7188, 463.7188,
        462.2636, 462.2636, 462.0839, 462.0839], dtype=torch.float64)
tensor([462.8607, 462.8607, 464.9398, 464.9398, 470.5648, 470.5648, 476.4546,
        476.4546, 549.6478, 549.6478, 635.3073, 635.3073, 652.0865, 648.6982,
        648.6982, 646.0998, 644.0226, 644.0226, 637.4882, 628.0352, 628.0352,
  